#!/bin/bash
#MSUB -A p30771
#MSUB -q short
#MSUB -l walltime=1:00:00
#MSUB -M johnjmarshall@u.northwestern.edu
#MSUB -j oe
#MSUB -N matlab_cnmfe_run
#MSUB -l nodes=1:ppn=20


cd ~

#add project directory to PATH
export PATH=$PATH/projects/p30771/

#load modules to use
module load python/anaconda3.6 

#need to cd to load conda environment

cd pythonenvs
cd CaImAn
source activate caiman

#need to cd to module directory

cd /home/jma819/caiman_data/demos/notebooks/caiman_analysis

# 

python mmap_to_h5py.py

